server:
  port: 8080
  session-timeout: 60
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

druid:
  url: jdbc:mysql://localhost:3306/test_data?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 5523380
  initial-size: 5
  min-idle: 1
  max-active: 100
  test-on-borrow: true

mybatis:
  type-aliases-package: com.iim.model
#  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.iim.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL

spring:
  datasource:
    schema: classpath:import.sql

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.233:3306/test_data
#    username: catuser
#    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
