server:
  port: 8080
  session-timeout: 60
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_data?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 5523380
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      maxWait: 10000
      StatViewServlet:
        loginUsername: demo
        loginPassword: demo
    schema: classpath:import.sql
  rabbitmq:
    addresses: 192.168.1.240:5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /

taskexecutor:
  corepoolsize: 5
  maxpoolsize: 20
  queuecapacity: 10
  threadnameprefix: ThreadPoolTaskExecutorByProject-

mybatis:
  type-aliases-package: com.iim.model.entity
#  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.iim.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

aws:
  bucketid: localdata
  basepath: demo/

oss:
  bucketid: localdata
  basepath: demo/





