server:
  port: 8080
  session-timeout: 60
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_data?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 5523380
    druid:
      initialSize: 5
      maxIdle: 2
      maxActive: 10
      maxWait: 10000
      StatViewServlet:
        loginUsername: demo
        loginPassword: demo
    schema: classpath:import.sql

mybatis:
  type-aliases-package: com.iim.model

mapper:
  mappers:
    - com.iim.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

aws:
  bucketid: localdata
  basepath: demo/

oss:
  bucketid: localdata
  basepath: demo/

